import Link from "next/link";
import { DenaPublicLayout, DenaRoleIcon } from "./dena-site-shell";

const catalogCourses = [
  { id:"chemistry-tenth", title:"شیمی دهم (کیهان و ساختار)", provider:"مؤسسه کنکور برتر", teacher:"استاد مریم سهرابی", sessions:"۲۸ جلسه", hours:"۲۲ ساعت محتوای آموزشی", price:"۴,۱۰۰,۰۰۰ تومان", supervised:false, image:"chemistry" },
  { id:"physics-tenth", title:"فیزیک دهم (مکانیک)", provider:"گروه ماز", teacher:"دکتر رضا علوی", sessions:"۲۰ جلسه", hours:"۱۵ ساعت محتوای آموزشی", price:"۳,۲۰۰,۰۰۰ تومان", supervised:true, image:"physics" },
  { id:"math-tenth", title:"ریاضی دهم تجربی و ریاضی", provider:"مؤسسه آموزشی نمونه", teacher:"استاد علیرضا احمدی", sessions:"۲۴ جلسه", hours:"۱۸ ساعت محتوای آموزشی", price:"۳,۸۰۰,۰۰۰ تومان", supervised:false, image:"math" },
  { id:"biology-tenth", title:"زیست‌شناسی دهم (پایه و مفاهیم)", provider:"آکادمی علوم فردا", teacher:"دکتر سارا حسینی", sessions:"۳۲ جلسه", hours:"۲۶ ساعت محتوای آموزشی", price:"۴,۵۰۰,۰۰۰ تومان", supervised:false, image:"biology" },
  { id:"arabic-tenth", title:"عربی دهم (ترجمه و قواعد)", provider:"گروه آموزشی مبین", teacher:"استاد محمد کریمی", sessions:"۱۶ جلسه", hours:"۱۲ ساعت محتوای آموزشی", price:"۲,۶۰۰,۰۰۰ تومان", supervised:true, image:"arabic" },
  { id:"literature-tenth", title:"ادبیات فارسی دهم", provider:"آموزشگاه اندیشه", teacher:"استاد نرگس رضایی", sessions:"۱۸ جلسه", hours:"۱۴ ساعت محتوای آموزشی", price:"۲,۹۰۰,۰۰۰ تومان", supervised:false, image:"literature" },
];

function Eyebrow({ children }: { children: React.ReactNode }) { return <span className="eyebrow">{children}</span>; }
function TitleBlock({ eyebrow, title, text }: { eyebrow?: string; title: string; text?: string }) {
  return <div className="site-title-block">{eyebrow && <Eyebrow>{eyebrow}</Eyebrow>}<h1>{title}</h1>{text && <p>{text}</p>}</div>;
}
function SiteCTA({ title, description, href="/courses", label="مشاهده دوره‌ها" }: { title:string; description:string; href?:string; label?:string }) {
  return <section className="site-cta"><h2>{title}</h2><p>{description}</p><Link className="dena-button dena-button--primary" href={href}>{label}</Link></section>;
}
function SampleTag() { return <span className="sample-tag">نمونهٔ نمایشی</span>; }

export function DenaCourseCatalogPage() {
  return <DenaPublicLayout>
    <section className="catalog-intro"><TitleBlock eyebrow="دوره‌های آموزشی دنا" title="دوره مناسب مسیر یادگیری‌ات را پیدا کن" text="دوره‌های آموزشی مؤسسات دارای مجوز و ارائه‌دهندگان تحت نظارت را بررسی کن، شرایط هر دوره را ببین و یادگیری را با سرعت خودت ادامه بده." /></section>
    <section className="catalog-content">
      <form className="catalog-search" action="/courses"><label className="sr-only" htmlFor="course-search">جست‌وجوی دوره</label><input id="course-search" name="q" placeholder="نام درس، دوره یا ارائه‌دهنده را جست‌وجو کن" /><button className="dena-button dena-button--primary" type="submit">جست‌وجو</button></form>
      <form className="catalog-filters" action="/courses">
        <label>درس<select name="subject"><option value="">همهٔ درس‌ها</option><option>ریاضی</option><option>فیزیک</option><option>شیمی</option></select></label>
        <label>پایه تحصیلی<select name="grade"><option value="">همهٔ پایه‌ها</option><option>دهم</option><option>یازدهم</option><option>دوازدهم</option></select></label>
        <label>وضعیت ارائه‌دهنده<select name="provider"><option value="">همه</option><option>مؤسسه دارای مجوز</option><option>ارائه‌دهنده تحت نظارت</option></select></label>
        <label>محدوده قیمت<select name="price"><option value="">همهٔ قیمت‌ها</option><option>کمتر از ۳ میلیون</option><option>۳ تا ۵ میلیون تومان</option></select></label>
        <Link href="/courses">پاک‌کردن فیلترها</Link>
      </form>
      <div className="catalog-grid">
        {catalogCourses.map((course)=><article className="course-card" key={course.title}>
          <div className={`course-card__image course-card__image--${course.image}`} role="img" aria-label={`تصویر دورهٔ ${course.title}`}><span className="course-card__image-label">پایه دهم · آموزش آفلاین</span></div>
          <div className="course-card__body">
            <div className="course-card__badges"><span>{course.sessions}</span><span className={course.supervised?"badge-supervised":"badge-licensed"}>{course.supervised?"ارائه‌دهنده تحت نظارت":"مؤسسه آموزشی دارای مجوز"}</span></div>
            <h2>{course.title}</h2><p>ارائه‌دهنده: {course.provider}<br />مدرس: {course.teacher}</p><small>پایه دهم · {course.hours}</small>
            <div className="course-card__price"><strong>{course.price}</strong><span>۴ قسط مساوی، بدون افزایش قیمت</span></div>
            <Link className="dena-button dena-button--outline" href={`/courses/${course.id}`}>مشاهده دوره</Link>
          </div>
        </article>)}
      </div>
      <p className="content-disclaimer">قیمت‌ها و عنوان‌های این صفحه نمونه‌اند. جزئیات قطعی هر دوره را ارائه‌دهندهٔ مسئول اعلام می‌کند.</p>
    </section>
    <section className="dena-section trust-strip"><h2>قبل از انتخاب، جزئیات هر دوره را ببین</h2><div className="trust-cards"><article>هویت ارائه‌دهنده و مؤسسهٔ ناظر روشن است</article><article>ساختار جلسات و محتوای دوره مشخص است</article><article>شرایط ارزیابی و پشتیبانی دوره اعلام می‌شود</article></div></section>
  </DenaPublicLayout>;
}

export function DenaCourseDetailsPage({ courseId = "physics-tenth" }: { courseId?: string }) {
  const course = catalogCourses.find((item) => item.id === courseId) ?? catalogCourses[1];
  return <DenaPublicLayout>
    <nav className="breadcrumbs" aria-label="مسیر صفحه"><Link href="/">خانه</Link><span>/</span><Link href="/courses">دوره‌ها</Link><span>/</span><span>فیزیک دهم (مکانیک)</span></nav>
    <section className="course-detail-hero">
      <div className={`course-detail-art course-card__image--${course.image}`} role="img" aria-label={`نمای معرفی دورهٔ ${course.title}`} />
      <div><SampleTag /><h1>{course.title}</h1><p>آشنایی ساختارمند با مفاهیم پایه، همراه با جلسات آموزشی ضبط‌شده، تمرین و ارزیابی برای پیگیری مسیر یادگیری.</p><div className="course-detail-meta"><span>آموزش آفلاین</span><span>پایه دهم</span><span>{course.supervised?"ارائه‌دهنده تحت نظارت":"مؤسسه دارای مجوز"}</span></div><div className="course-detail-price"><strong>{course.price}</strong><span>۴ قسط مساوی، بدون افزایش قیمت</span><small>مبلغ کل دوره در پرداخت اقساطی افزایش نمی‌یابد.</small></div><Link className="dena-button dena-button--primary" href="/login">ورود برای ثبت‌نام در دوره</Link></div>
    </section>
    <section className="dena-section detail-outcomes"><TitleBlock eyebrow="دستاوردهای یادگیری" title="پس از این دوره چه چیزهایی یاد می‌گیری؟" text="این دوره نمونه‌ای از مسیر محتوای آموزشی و ارزیابی است؛ برنامهٔ نهایی را مؤسسهٔ مسئول دوره تعیین می‌کند."/><div className="detail-card-grid">{["درک کمیت‌های فیزیکی و اندازه‌گیری","تحلیل بردارها و حرکت","حل مسئله با تمرین‌های مرحله‌ای","مرور آموخته‌ها با ارزیابی مرتبط"].map((x,i)=><article key={x}><b>۰{i+1}</b><h3>{x}</h3></article>)}</div></section>
    <section className="dena-section detail-structure"><TitleBlock title="ساختار دوره" text="جلسه‌ها و تمرین‌ها در ترتیب پیشنهادی مؤسسه قرار می‌گیرند."/><div className="lesson-list"><article><span>جلسه ضبط‌شده</span><b>جلسه ۱: معرفی مکانیک و کمیت‌های فیزیکی</b></article><article><span>جلسه ضبط‌شده</span><b>جلسه ۲: بردارها و محاسبات جمع برداری</b></article><article><span>تمرین</span><b>تمرین فصل اول: تحلیل ابعادی و بردارها</b></article></div></section>
    <section className="dena-section"><TitleBlock title="تمرین‌ها و آزمون‌های مرتبط با دوره" text="تمرین‌ها و آزمون‌ها برای بررسی آموخته‌ها و ثبت نتایج به مسیر یادگیری متصل می‌شوند."/><div className="trust-cards"><article><h3>تمرین‌های مرتبط</h3><p>تمرین‌های مباحث دوره برای سنجش و تثبیت آموخته‌ها.</p></article><article><h3>آزمون‌های دوره</h3><p>آزمون‌های مرتبط با سرفصل‌ها برای بررسی آموخته‌ها.</p></article><article><h3>ثبت نتیجه و پیشرفت</h3><p>نمایش نتایج ارزیابی در بخش مسیر رشد دانش‌آموز.</p></article></div></section>
    <section className="content-disclaimer-block"><b>مسئولیت آموزشی دوره</b><p>قیمت‌گذاری، محتوای دوره، تمرین‌ها، آزمون‌ها و پشتیبانی بر عهدهٔ ارائه‌دهنده و مؤسسهٔ ناظر است. دنا بستر اتصال و مشاهدهٔ مسیر یادگیری را فراهم می‌کند.</p></section>
    <SiteCTA title="یادگیری این دوره را شروع کن" description="برای ورود به حساب کاربری و پیگیری دوره ادامه بده." href="/login" label="ورود به دنا" />
  </DenaPublicLayout>;
}

const roleCards = [["دانش‌آموز","محور یادگیری و مسیر رشد فردی","student"],["مؤسسه آموزشی","ارائه‌دهنده رسمی دوره‌ها و مسئول مستقیم آموزش","institute"],["ارائه‌دهنده تحت نظارت","ارائهٔ دوره با نظارت مؤسسهٔ دارای مجوز","provider"],["سازمان و حامی","تسهیل دسترسی منصفانه به فرصت‌های رشد","supporter"]];
function RoleCards() { return <div className="role-grid">{roleCards.map(([name,description,key])=><article className={`role-card role-card--${key}`} key={key}><span className="role-card__icon" aria-hidden="true"><DenaRoleIcon kind={key}/></span><h3>{name}</h3><p>{description}</p></article>)}</div>; }
function NetworkGraphic() { return <div className="network-art" aria-hidden="true"><i/><i/><i/><i/><i/><i/><b/><b/><b/></div>; }

export function DenaEliteClubPage() {
  return <DenaPublicLayout><section className="site-split-hero"><NetworkGraphic/><div><Eyebrow>باشگاه نخبگان دنا</Eyebrow><h1>استعدادها در کنار هم شکوفا می‌شوند</h1><p>باشگاه نخبگان بخشی از مسیر یادگیری و رشد در دناست؛ فضایی برای توجه به توانایی‌ها و حرکت جمعی رو به آینده.</p><Link className="dena-button dena-button--primary" href="/login">ورود به دنا</Link></div></section><section className="dena-section"><TitleBlock title="باشگاه نخبگان؛ نگاه نوآفرینانه، رشد از اتصال"/><div className="trust-cards"><article><h3>نگاه نوآفرینانه</h3><p>توجه به ایده‌ها و فرصت‌های تازه برای نوآفرینی، در ادامهٔ مسیر رشد دانش‌آموز.</p></article><article><h3>ارتباط و هم‌افزایی</h3><p>پیوند میان دانش‌آموزان و بخش‌های اکوسیستم با تمرکز بر یادگیری و رشد جمعی.</p></article><article><h3>رشد استعدادها</h3><p>توجه به علایق و توانایی‌های دانش‌آموز در کنار مسیر یادگیری او در دنا.</p></article></div></section><section className="dena-section roles-panel"><TitleBlock title="نقش‌ها در اکوسیستم دنا"/><RoleCards/><div className="role-note"><div><h3>استعداد و یادگیری، در یک مسیر به‌هم‌پیوسته</h3><p>باشگاه نخبگان جایگزین آموزش مؤسسه نیست و مسیر یادگیری را تکمیل می‌کند.</p></div><div><h3>رشد استعدادها با همراهی</h3><p>مؤسسه و تیم آموزشی مسئول همراهی آموزشی هر دوره هستند.</p></div></div></section><SiteCTA title="رشد در کنار هم، در اکوسیستم دنا" description="مسیرهای یادگیری و رشد را در دنا ببین." href="/about" label="آشنایی با دنا" /></DenaPublicLayout>;
}

export function DenaGrowthPathPage() {
  return <DenaPublicLayout><section className="growth-page-intro"><TitleBlock eyebrow="مسیر رشد دنا" title="روند یادگیری‌ات را در طول زمان ببین" text="پیشرفت جلسات آموزشی، تمرین‌ها، نتایج آزمون‌ها و عملکرد درسی در کنار هم نمایش داده می‌شوند تا مسیر رشد یا افت یادگیری روشن‌تر شود."/></section><section className="dena-section growth-page-content"><div className="growth-page-copy"><SampleTag/><h2>رشدت را فقط حس نکن؛ ببین</h2><p>در دنا، پیشرفت دوره، نتایج آزمون‌ها، تمرین‌ها و عملکرد درسی در طول زمان کنار هم قرار می‌گیرند تا دانش‌آموز بتواند روند رشد یا افت خود را ببیند و برای قدم بعدی مسیر یادگیری آماده شود.</p><div className="report-note"><b>روند کلی شما رو به رشد است</b><span>نمونهٔ داده برای نمایش طراحی</span></div><div className="report-note report-note--warning"><b>کاهش موقت عملکرد در فیزیک</b><span>مرور درس در قدم بعدی</span></div></div><div className="growth-report"><div className="growth-report__top"><span>مسیر رشد من · روند ۶ ماه اخیر</span><strong>+۱۲٪</strong></div><div className="growth-report__chart"><i/><i/><i/><i/><i/><i/></div><div className="growth-report__labels"><span>آبان</span><span>آذر</span><span>دی</span><span>بهمن</span><span>اسفند</span><span>فروردین</span></div><div className="growth-stats"><article><b>+۱۲٪</b><span>رشد محسوس · ریاضی</span></article><article><b>−۴٪</b><span>افت موقت · فیزیک</span></article><article><b>+۱٪</b><span>ثبات تحصیلی · شیمی</span></article></div></div></section><section className="dena-section"><TitleBlock title="مسیر رشد از چه داده‌هایی ساخته می‌شود؟"/><div className="trust-cards"><article><h3>روند عملکرد درسی</h3><p>تغییرات عملکرد هر درس در طول زمان قابل مشاهده می‌شود.</p></article><article><h3>تمرین و آزمون</h3><p>نتایج ارزیابی‌های مرتبط با دوره در طول مسیر ثبت و نمایش داده می‌شود.</p></article><article><h3>پیشرفت دوره</h3><p>جلسه‌های تکمیل‌شده و میزان پیشروی در هر دوره بخشی از مسیر یادگیری است.</p></article></div></section><section className="content-disclaimer-block"><h2>مسئولیت و حریم داده</h2><p>مسیر رشد به داده‌هایی متکی است که مؤسسه یا ارائه‌دهندهٔ مسئول در چارچوب دوره ثبت می‌کند. این نمایش نمونه است و دادهٔ واقعی دانش‌آموزی در آن وجود ندارد.</p></section><SiteCTA title="یادگیری‌ات را ادامه بده" description="برای دیدن مسیر رشد شخصی وارد حساب دانش‌آموزی شو." href="/login" label="ورود دانش‌آموز"/></DenaPublicLayout>;
}

export function DenaAssessmentsPage() {
  return <DenaPublicLayout><section className="catalog-intro"><TitleBlock eyebrow="ارزیابی آموزشی" title="ارزیابی، پیوسته با مسیر یادگیری" text="تمرین‌ها و آزمون‌های مرتبط با دوره توسط مؤسسه یا ارائه‌دهندهٔ مربوط مدیریت می‌شوند و نتایجشان در مسیر رشد دانش‌آموز نمایش داده می‌شود."/></section><section className="dena-section assessment-sample"><div className="assessment-card"><SampleTag/><h2>آزمون سنجش مستمر فصل ۳</h2><p>فیزیک دهم · مؤسسهٔ آموزشی البرز</p><div className="assessment-card__facts"><span>۲۰ پرسش</span><span>زمان پیشنهادی: ۳۰ دقیقه</span><span>نتیجه در مسیر رشد</span></div><Link className="dena-button dena-button--primary" href="/login">ورود برای مشاهده</Link></div><div className="assessment-explanation"><Eyebrow>نقش ارزیابی</Eyebrow><h2>آزمون بخشی از فرایند یادگیری است</h2><p>ارزیابی‌ها به دوره و سرفصل آموزشی مربوط می‌شوند. مؤسسهٔ مسئول دوره، تمرین و آزمون را طراحی و مدیریت می‌کند.</p><p className="content-disclaimer">این کارت نمونهٔ نمایشی است؛ آزمون واقعی در این صفحه برگزار نمی‌شود.</p></div></section><section className="dena-section"><TitleBlock title="آزمون در دنا چه جایگاهی دارد؟"/><div className="trust-cards"><article><h3>آزمون مرتبط با دوره</h3><p>ارزیابی به محتوای دوره و سرفصل‌های آموزشی مربوط است؛ دنا برگزارکنندهٔ مستقل آموزش نیست.</p></article><article><h3>ثبت نتایج ارزیابی</h3><p>نتایج آزمون‌ها و تمرین‌های دوره در مسیر یادگیری ثبت می‌شوند و قابل مشاهده‌اند.</p></article><article><h3>روند عملکرد درسی</h3><p>نتایج در کنار تمرین‌ها و پیشرفت دوره مسیر رشد را روشن‌تر می‌کند.</p></article></div></section><section className="content-disclaimer-block"><h2>مسئولیت آزمون</h2><p>محتوا، زمان‌بندی، ارزیابی و پاسخ‌گویی آموزشی بر عهدهٔ مؤسسه یا ارائه‌دهندهٔ مسئول دوره است.</p></section><SiteCTA title="ارزیابی را در مسیر دوره دنبال کن" description="دوره‌های آموزشی را ببین و تمرین‌ها و آزمون‌های مرتبط را بررسی کن."/></DenaPublicLayout>;
}

export function DenaAboutPage() {
  return <DenaPublicLayout><section className="site-split-hero"><NetworkGraphic/><div><Eyebrow>درباره دنا</Eyebrow><h1>یک اکوسیستم برای اتصال مسیرهای یادگیری</h1><p>دنا بستری یکپارچه برای اتصال دانش‌آموز، مؤسسات آموزشی، ارائه‌دهندگان و حامیان است تا مسیر یادگیری و رشد روشن‌تر شود.</p><Link className="dena-button dena-button--primary" href="/courses">دوره‌های دنا</Link></div></section><section className="dena-section"><TitleBlock title="وقتی یکی رشد می‌کند، همه جلو می‌روند" text="دنا بازارگاه جدا از فرایند یادگیری نیست؛ بستر اتصال و پیگیری مسیر یادگیری است. مسئولیت آموزش و همراهی تحصیلی با مؤسسه یا ارائه‌دهندهٔ مربوط است."/><RoleCards/></section><section className="dena-section about-platform"><div><Eyebrow>بستر اتصال و هماهنگی</Eyebrow><h2>دنا چگونه یادگیری را به هم پیوند می‌دهد؟</h2><p>جلسه‌های آموزشی، نتایج آزمون‌ها و عملکرد درسی در یک مسیر قابل پیگیری نمایش داده می‌شوند.</p></div><div className="trust-cards"><article><h3>نمایش مسیر رشد</h3><p>پیشرفت جلسات و تغییرات عملکرد در طول زمان.</p></article><article><h3>تمرین و ارزیابی</h3><p>تمرین و آزمون هر دوره به فرایند یادگیری متصل است.</p></article><article><h3>دسترسی یکپارچه</h3><p>دوره‌های مؤسسات در یک بستر قابل بررسی و پیگیری‌اند.</p></article></div></section><SiteCTA title="در دنا، آموزش تنها نیست؛ رشد همراه است" description="دوره‌ها، آزمون‌ها، مسیر رشد و باشگاه نخبگان را در یک اکوسیستم پیوسته بشناس." href="/elite-club" label="باشگاه نخبگان"/></DenaPublicLayout>;
}

export function DenaInstituteCollaborationPage() {
  return <DenaPublicLayout><section className="institute-banner"><div><Eyebrow>ویژه مؤسسات آموزشی</Eyebrow><h1>به اکوسیستم دنا بپیوندید</h1><p>دوره‌های آموزشی خود را با هویت مؤسسه، ارزیابی و همراهی تحصیلی در بستری یکپارچه ارائه کنید.</p><div className="dena-hero__actions"><Link className="dena-button dena-button--primary" href="/institutes/request">ثبت درخواست همکاری</Link><Link className="dena-button dena-button--outline" href="/about">درباره دنا</Link></div></div><ul><li>دوره‌ها با هویت خود مؤسسه</li><li>پیگیری آموزشی در یک مسیر منسجم</li><li>مدیریت قیمت و ارزیابی توسط مؤسسه</li></ul></section><section className="dena-section"><TitleBlock title="همکاری با دنا؛ نقش‌های روشن"/><div className="trust-cards"><article><h3>همراهی و مسیر رشد</h3><p>مؤسسه همراهی تحصیلی را انجام می‌دهد و دنا روند یادگیری را نمایش می‌دهد.</p></article><article><h3>قیمت، تمرین و ارزیابی</h3><p>قیمت‌گذاری، تمرین‌ها و آزمون‌های دوره بر عهدهٔ مؤسسه یا ارائه‌دهنده است.</p></article><article><h3>هویت و مالکیت محتوا</h3><p>دوره‌های ضبط‌شده با هویت مؤسسه منتشر می‌شوند و حقوق محتوا نزد صاحب آن می‌ماند.</p></article></div></section><section className="dena-section institute-roles"><div><Eyebrow>نقش‌ها در همکاری آموزشی</Eyebrow><h2>نظارت آموزشی با مؤسسهٔ دارای مجوز است</h2><p>هر دوره باید مسئول آموزشی روشن داشته باشد. ارائه‌دهندهٔ تحت نظارت فقط با تأیید مؤسسه و برای دورهٔ مشخص فعالیت می‌کند.</p></div><RoleCards/></section><SiteCTA title="مؤسسهٔ آموزشی هستید؟ با دنا همراه شوید" description="دوره‌های آفلاین خود را با هویت مؤسسه، ارزیابی و همراهی تحصیلی ارائه کنید." href="/institutes/request" label="ثبت درخواست همکاری"/></DenaPublicLayout>;
}

export function DenaInstituteRequestPage() {
  return <DenaPublicLayout><section className="catalog-intro"><TitleBlock eyebrow="همکاری با دنا" title="درخواست همکاری مؤسسهٔ آموزشی" text="اطلاعات مؤسسه را ثبت کنید تا درخواست برای بررسی اولیه آماده شود."/></section><section className="dena-section institute-form-layout"><aside><h2>پس از ارسال درخواست</h2><p>اطلاعات برای بررسی اولیه استفاده می‌شوند. ارسال فرم به‌تنهایی به معنای تأیید مجوز یا شروع همکاری نیست.</p><ol><li>بررسی اطلاعات و هویت مؤسسه</li><li>بررسی مدارک مجوز آموزشی</li><li>تماس برای تکمیل فرایند همکاری</li></ol><div className="content-disclaimer-block"><b>دقت اطلاعات</b><p>فقط اطلاعاتی را ثبت کنید که مجاز به ارائهٔ آن هستید.</p></div></aside><form className="institute-request-form" action="/institutes/request/confirmation" method="get"><h2>فرم درخواست همکاری</h2><p>فیلدهای ستاره‌دار الزامی هستند.</p><div className="request-fields"><label>نام رسمی مؤسسه *<input required name="instituteName" /></label><label>شناسه ملی *<input required name="nationalId" inputMode="numeric" /></label><label>نام و نام خانوادگی نماینده *<input required name="representative" /></label><label>سمت نماینده *<input required name="position" /></label><label>شماره همراه *<input required name="phone" inputMode="tel" /></label><label>ایمیل سازمانی<input name="email" type="email" /></label><label>استان و شهر *<input required name="location" /></label><label>وب‌سایت مؤسسه<input name="website" type="url" /></label><label className="request-fields__wide">توضیح کوتاه دربارهٔ دوره‌ها و زمینهٔ همکاری<textarea name="description" rows={4}/></label></div><label className="request-consent"><input type="checkbox" required /> صحت اطلاعات بالا را تأیید می‌کنم و می‌دانم این فرم فقط درخواست اولیه است.</label><p className="content-disclaimer">این فرم در نسخهٔ نمایشی اطلاعات را ذخیره یا ارسال نمی‌کند.</p><button className="dena-button dena-button--primary" type="submit">ثبت درخواست برای بررسی</button></form></section></DenaPublicLayout>;
}

export function DenaInstituteConfirmationPage() {
  return <DenaPublicLayout><section className="confirmation-state"><span className="confirmation-check" aria-hidden="true">✓</span><Eyebrow>وضعیت درخواست</Eyebrow><h1>درخواست شما آمادهٔ بررسی است</h1><p>این صفحه فقط وضعیت نمایشی فرم را نشان می‌دهد. در نسخهٔ نمایشی هیچ اطلاعاتی ذخیره یا برای دنا ارسال نشده است.</p><div className="content-disclaimer-block"><b>مراحل بعدی</b><p>در فرایند عملیاتی، اطلاعات مؤسسه و مدارک مجوز بررسی می‌شود؛ سپس برای ادامهٔ همکاری با نماینده تماس می‌گیریم.</p></div><Link className="dena-button dena-button--primary" href="/">بازگشت به صفحهٔ اصلی</Link></section></DenaPublicLayout>;
}
